trigger: none

parameters:
  - name: environment
    displayName: Environment
    type: string
    default: dev
    values:
    - dev
    - prod

pool:
  vmImage: windows-latest

steps:
- task: DownloadBuildArtifacts@1
  displayName: 'Download Build Artifacts'
  inputs:
    buildType: specific
    project: 'Automation'
    pipeline: 'app ci'
    artifactName: 'drop'
    downloadPath: '$(Build.ArtifactsDirectory)'
- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: $(connection-type)
    azureSubscription: $(subscription)
    appType: $(app-type)
    WebAppName: 'app-$(app-name)-${{ parameters.environment }}-$(location)-00'
    package: '$(Build.Repository.LocalPath)\$(Build.ArtifactsDirectory)\drop/WebApp.zip'
    