resources:
  repositories:
    - repository: InternshipApp
      type: azureRepo
      name: YourAzureProject/YourRepoName
      ref: refs/heads/develop
jobs:
- job: Build
  displayName: 'Build .NET 6 App'
  pool:
    vmImage: 'windows-latest'
  steps:
  - checkout: self
  - checkout: InternshipApp
    path: 'PlanePal'  # Specify the target folder where you want to clone the repository
  - task: UseDotNet@2
    inputs:
      packageType: 'sdk'
      version: '6.x'  # Replace with the desired .NET 6 version
      installationPath: $(Agent.ToolsDirectory)/dotnet
  - script: |
      cd PlanePal
      dotnet build
    displayName: 'Build .NET 6 App in PlanePal'