trigger:
- none

variables:
- group: infrastructure-group

pool:
  vmImage: ubuntu-latest

steps:
- task: TerraformInstaller@1
  inputs:
    terraformVersion: 'latest'

- task: TerraformTaskV4@4
  inputs:
    provider: 'azurerm'
    command: 'init'
    commandOptions: -backend-config="resource_group_name=$(resource-group)" \
                    -backend-config="storage_account_name=$(storage-account)" \
                    -backend-config="container_name=$(container-name)" \
                    -backend-config="key=$(tfstate-key)"

    backendServiceArm: $(subscription)
    backendAzureRmResourceGroupName: $(resource-group)
    backendAzureRmStorageAccountName: $(storage-account)
    backendAzureRmContainerName: $(container-name)
    backendAzureRmKey: $(tfstate-key)

- task: TerraformTaskV4@4
  inputs:
    provider: 'azurerm'
    command: 'validate'
    
- task: TerraformTaskV4@4
  inputs:
    provider: 'azurerm'
    command: 'plan'
    # commandOptions: '-out=plan'
    environmentServiceNameAzureRM: $(subscription)
