trigger:
- none

pool:
  vmImage: 'windows-latest'

variables:
  solution: 'PlanePal/**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

resources:
  repositories:
    - repository: InternshipApp  # Unique name for the external repository
      type: git  # Replace with the appropriate repository type (GitHub, Azure DevOps, etc.)
      name: YourGitHubUsername/InternshipApp  # Replace with the actual repository URL or name
      ref: refs/heads/develop  # Specify the branch you want to use


jobs:
- job: Build
  pool:
    vmImage: 'windows-latest'
  steps:
  - checkout: self
  - checkout: InternshipApp  # Checkout the external repository
  - script: |
      # Your build steps here
    displayName: 'Build InternshipApp'
  - task: NuGetToolInstaller@1

  - task: NuGetCommand@2
    inputs:
      restoreSolution: '$(solution)'

  - task: VSTest@2

  - script: dotnet build --configuration $(buildConfiguration)
    displayName: 'dotnet build $(buildConfiguration)'

  - task: DotNetCoreCLI@2
    inputs:
      command: 'publish'
      arguments: '--configuration $(buildConfiguration) -o $(Build.ArtifactStagingDirectory)/Output'
      publishWebProjects: true

