trigger:
- none

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

  resources:
  repositories:
  - repository: InternshipApp
    type: git
    name: InternshipApp
    ref: develop

stages:
- stage: BuildAndTest
  jobs:
  - job: DeployToAzure
    steps:
    - checkout: InternshipApp 
  - job: Build
    steps:
    - task: NuGetToolInstaller@1

    - task: NuGetCommand@2
      inputs:
        restoreSolution: '$(solution)'
    - task: VSTest@2

    - script: dotnet build --configuration $(buildConfiguration)
      displayName: 'dotnet build $(buildConfiguration)'


