trigger: none

pool:
  vmImage: windows-latest

steps:


- task: DownloadPipelineArtifact@2
  inputs:
    buildType: 'specific'
    project: 'ec5b5ca8-a182-4c12-a41b-fb5307fec395'
    definition: '14'
    #buildVersionToDownload: 'latestFromBranch'
    #branchName: 'main'
    targetPath: '$(Pipeline.Workspace)'
  

- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Levi9Internship2023SP-Automation'
    appType: 'webApp'
    WebAppName: 'app-PlanePal-dev-northeurope-00'
    Package: '$(Pipeline.Workspace)/**/*.zip'