trigger: none

pool:
  vmImage: windows-latest

steps:
- task: DownloadBuildArtifacts@1
  displayName: 'Download Build Artifacts'
  inputs:
    buildType: specific
    project: 'Automation'
    pipeline: 'CI App'
    artifactName: 'drop'
    downloadPath: '$(Build.ArtifactsDirectory)'
- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Levi9Internship2023SP-Automation'
    appType: 'webApp'
    WebAppName: 'app-PlanePal-dev-northeurope-00'
    package: '$(Build.ArtifactStagingDirectory)/**/*.zip'
    