trigger: none

pool:
  vmImage: windows-latest

steps:
- task: DownloadBuildArtifacts@1
  inputs:
    buildType: 'current'
    downloadType: 'single'
    artifactName: 'drop'
    downloadPath: '$(System.ArtifactsDirectory)'
- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Levi9Internship2023SP-Automation'
    appType: 'webApp'
    WebAppName: 'app-PlanePal-dev-northeurope-00'
    package: '$(Build.ArtifactStagingDirectory)/**/*.zip'
    